### ISSUE TITLE
GetMassListFromScanNum equivalent in Python / dotNET

### ISSUE THREAD

**Issue by keesh0** [ethz-institute-of-microbiology/fisher_py#9]
Hello,
Not really an issue, 
but wondering the equivalent call from older C++ interface XRawfile::IXRawfile2Ptr GetMassListFromScanNum() in the new dotNet / Python world?
thx e.-

**Comment by dowerner** [comment]
Hi @keesh0,
Since I am not familiar with the C++ library you are describing and am not affiliated with Thermo Fisher in any way, I can only
 provide you some hints.

1. Have a look at the examples and, maybe you'll find something useful.
2. The RawFileAccess class should provide you all the scan events in your file:
```python
scan_event = raw_file_access.scan_events.get_event(my_scan_num)
masses = scan_event.get_mass_range(idx)
```

**Comment by keesh0** [comment]
The following appeared to work for me:
raw_file.get_centroid_stream() and
raw_file.get_segmented_scan_from_scan_number().

**Comment by dowerner** [comment]
I am glad to hear that you found something that suits your needs. If you open the RawFile code you see that it is pretty much just a wrapper for the RawFileAccess class. This might help you if there are requirements which are not covered by RawFile. Closing the issue for now.

**Comment by schatzsc** [comment]
I think part of the confusion is due to unclear terminology. In my domain, which is mostly small molecule inorganic chemistry, centroid-style mass spectra are not really used anymore and we almost exclusively work with "profile spectra".

However, something I was not aware of until now is that at least ThermoFisher *.raw files do not store the full scan range as intensity vs. m/z, as it is done in NMR, IR, and UV/Vis spectroscopy, where you really have x/y pairs of data over the full range, but only "peak regions" with a little bit of zeros to the left and right.

When you think about it, it actually makes a lot of sense not to store tons of close to zero values, as scan range in mass spectrometry is much wider than in the other methods and at the same time with high-resolution mass analyzers also records much more data points per unit of x-axis.

So I think the key for me was to realize that the "segmented scan" is actually the "profile scan" that I need.

It's really just that it did not show up under the name I expected.
